In [31]:
import pandas as pd
import numpy as np

In [32]:
debug=0

notesNom="/Users/gilles/Downloads/LNS1M41 Notes-Majeure.csv"
notesNom=u"/Users/gilles/Downloads/LNS1U4-LNS1T2-NotesMineures.csv"
notesNom=u"/Users/gilles/Downloads/LNS1U4-LNS1T2-NotesMajeure.csv"
notesNom=u"/Users/gilles/Downloads/LNS2U2-QuizzBonus.csv"
dfNotes=pd.read_csv(notesNom,sep="\t",encoding="utf8")

dfNotes.set_index([u'Nom', u'Prénom'],inplace=True)

⚠️ Attention à fournir un fichier XLSX

In [33]:
notesNom=u"/Users/gilles/sDrive/Cours/Bordeaux/L1-LinguistiqueGenerale/NotesCours/25-Session1/25-1LNSU4.xlsx"

In [34]:
xls = pd.ExcelFile(notesNom)
xls.sheet_names

[u'Notes']

In [41]:
# dfNotes=pd.read_excel(notesNom,encoding="utf8")
dfNotes = pd.read_excel(xls, sheet_name=u'Notes',encoding="utf8")
dfNotes[u"Numéro d’identification"]=dfNotes[u"Numéro d’identification"].astype("int").astype("str")
dfNotes.set_index([u"Numéro d’identification"],inplace=True)
len(dfNotes.columns)

22

In [45]:
dfNotes.columns=[u'Nom', u'Prénom', u'Adresse de courriel',u'Prasi', u'Yomig V', u'Yomig T', u'Kartin V', u'Kartin T', u'Nemas V', u'Nemas T', u'CoupeMot', u'CoupeMorphe']+sorted([u"Q%02d"%(n+1) for n in range(1,11)])

len(dfNotes.columns)

22

#### sélection des colonnes
- notesCC pour le contrôle continu
- notesQuizz pour les quizz en CM

In [46]:
notesCC=[u'Prasi', u'Yomig V', u'Yomig T', u'Kartin V', u'Kartin T', u'Nemas V', u'Nemas T',
         u'CoupeMot', u'CoupeMorphe'
        ]
# notesCC=u"Morpho1 Morpho2 Bizar1 Bizar2 Phono Sem".split(" ")
# notesQuizz=sorted([u"Quizz%d"%(n+1) for n in range(2,8)]+[u"Quizz7b"])
notesQuizz=sorted([u"Q%02d"%(n+1) for n in range(1,11)])
# dfNotes=dfNotesXLS[notesCC+notesQuizz]
dfNotes[notesQuizz].head(10)

                        Q02 Q03 Q04 Q05 Q06 Q07 Q08 Q09 Q10 Q11
Numéro d’identification
455717                    -   -   -   -   -   -   -   -   -   -
429665                    -   -   -   -   -   -   -   -   -   -
461076                    -   -   -   -   -   -   -   -   -   -
458113                   19  16  13  17  14  10  17  15  15  13
396581                   19  14  13  19  18  16  20  13  15  12
459692                   20   0   7  16  14  13  13  18  17  13
446215                    -   -   -   -   -   -   -   -   -   -
435583                    -   -   -   -   -   -   -   -   -   -
414295                   20  20  11  20  14  14  10  13  17  15
461104                   14   -   -   -   -   -   -   -   -   -

### Calcul des notes avec bonification
Toutes les notes du CC (*nbCC*) comptent et on inclue aussi les *nbCC* meilleures notes des Quizz en partant de la meilleure une par une
- *notes* contient toutes les moyennes calculées
- on retourne le max de *notes*

In [47]:
def moyenneCC(x):
    if debug: print x.name
    xNotesCC=sorted([n for n in x[notesCC].tolist() if not (n=="-" or np.isnan(n))],reverse=True)
    sommeNotes=float(sum(xNotesCC))
    nbNotes=len(notesCC)
    moyenneInitiale=round(sommeNotes/nbNotes+.25)
    return moyenneInitiale

In [48]:
def bonus(x):
    if debug: print x.name
    xNotesCC=sorted([n for n in x[notesCC].tolist() if not (n=="-" or np.isnan(n))],reverse=True)
    sommeNotes=float(sum(xNotesCC))
    nbNotes=len(notesCC)
    moyenneInitiale=round(sommeNotes/nbNotes+.25)
    xNotesBonus=sorted([n for n in x[notesQuizz].tolist() if not (n=="-" or np.isnan(n))],reverse=True)
    if debug: print "Quizz",xNotesBonus
    if debug: print "CC",xNotesCC
    if xNotesCC:
        notes=[]
        nbCC=len(xNotesCC)
        bonusNotes=xNotesBonus
        if len(bonusNotes)>nbCC:
            bonusNotes=bonusNotes[:nbCC]
        notes.append(moyenneInitiale)
        if debug: print "somme", sommeNotes,"moyenne brut",sommeNotes/nbNotes
        if debug: print "moyenne initiale",moyenneInitiale,"bonus",bonusNotes
        for b in bonusNotes:
            sommeNotes+=b
            nbNotes+=1
            nouvelleMoyenne=round(float(sommeNotes)/nbNotes+.25)
            notes.append(nouvelleMoyenne)
            if debug: print b,sommeNotes,nbNotes, nouvelleMoyenne
        if debug: print notes
        return max(notes)
    else:
        return np.nan

### Ajout de la colonne **Notes** à la structure et exportation
- apply(lambda x: bonus(x), axis=1) permet d'appliquer la fonction bonus à chaque ligne
 - la fonction bonus reçoit une ligne de données complète
 - les valeurs sont accessibles par colonne
- on ajoute 3 colonnes
 - Note pour la note de contrôle continu avec les bonus de quizz
 - NoteCC pour la note des exercices en ligne brute
 - Gain pour la différence entre les deux notes

In [49]:
dfNotes.loc[:,"Note"]=dfNotes.loc[:,notesCC+notesQuizz].apply(lambda x: bonus(x),axis=1)
dfNotes.loc[:,"NoteCC"]=dfNotes.loc[:,notesCC].apply(lambda x: moyenneCC(x),axis=1)

In [50]:
dfNotes["Gain"]=dfNotes["Note"]-dfNotes["NoteCC"]

In [51]:
dfNotes["Gain"].mean()

2.2247191011235956

In [52]:
dfNotes[dfNotes["Note"].notnull()][u"Prénom Nom Note NoteCC Gain".split(" ")]

                              Prénom                  Nom  Note  NoteCC  Gain
Numéro d’identification
429665                          LINA           ABDELJALIL   0.0     0.0   0.0
458113                         NELIA            AGLETINER  12.0     8.0   4.0
396581                         LWANN                ALBON  11.0     5.0   6.0
459692                        ADELIE                ALMON  13.0    11.0   2.0
446215                       SERIANE              ALTENOR   0.0     0.0   0.0
435583                          NELL               ANDRAC   6.0     6.0   0.0
414295                       TIMOTHY              ANDRADE  15.0    12.0   3.0
461104                         JULIA                ANOGE   2.0     1.0   1.0
458613                         CHLOE               ARTOLA  10.0     5.0   5.0
456651                         MAELA              AUGUSTE  17.0    16.0   1.0
457795                          LILY               BARBRY   4.0     3.0   1.0
434036                        AHCENE            BENAOUDIA   5.0     1.0   4.0
457173                      MATHILDE            BESSONART   7.0     4.0   3.0
454875                         ANAIS           BONETBELTS  14.0    12.0   2.0
460512                     VALENTINE                BOUIN   0.0     0.0   0.0
458727                          LINA         BOURCHACHENE   2.0     0.0   2.0
416701                        OMEIMA              BOUREMA   2.0     0.0   2.0
458609                          NINA              CALLEDE   3.0     0.0   3.0
459964                       MARGAUX            CAMBARRAT   0.0     0.0   0.0
446384                      JULIETTE                CAMUT  14.0    12.0   2.0
456710                          SEMA                CANLI  10.0     7.0   3.0
457965                          LILA              CAPRAJA   7.0     5.0   2.0
455667                      TIMOTHEE            CARRASSET   5.0     2.0   3.0
453789                         CHLOE             CARTIGNY   4.0     0.0   4.0
459406                         ELISA              COUREAU   6.0     2.0   4.0
459136                      ELEONORE     COURTOT--COUSSEL   4.0     1.0   3.0
453815                       LOUHANE               CROWIN   9.0     4.0   5.0
460429                          NOAH               DALMAS   1.0     1.0   0.0
458313                          EMMA             DARRICAU   8.0     5.0   3.0
458657                        OCEANE           DE FREITAS  16.0    15.0   1.0
...                              ...                  ...   ...     ...   ...
459959                       JUSTINE           LOUSTAUNAU   2.0     0.0   2.0
457111                        JOAKIM                LUBIN   9.0     3.0   6.0
457483                         ELISA              LUCANTE   6.0     2.0   4.0
460583                       KHALIDA                 MADI   3.0     0.0   3.0
458207                      MATHILDE              MAJERUS   7.0     3.0   4.0
457731                         ANAIS                MANUS   9.0     5.0   4.0
453211                     CHARLOTTE    MARIAGE--CORNILLE  12.0    10.0   2.0
453892                           ZOE            MAROSTICA   6.0     2.0   4.0
459942                     CONSTANCE              MERCIER   0.0     0.0   0.0
456686                      TIPHAINE            MIGNARDOT  12.0    10.0   2.0
454079                       MATHIEU            MONTEILLE  10.0     6.0   4.0
451482                       BLANCHE              NAVARRO   0.0     0.0   0.0
460169                        MINTOU               NDIAYE   2.0     0.0   2.0
463562                        GIULIA               NISINI   2.0     1.0   1.0
454852                         MANON              OLIVIER   8.0     3.0   5.0
460344                       ALBANNE  PAGNOUX--PELLEGRINO   6.0     3.0   3.0
458010                         LUCIA              PELANNE   8.0     4.0   4.0
454341                        MAELLE    POVEDA-DURASTANTI   3.0     1.0   2.0
462574                        SIMONE          PRISCA VAVY   7.0     3.0   4.0
426755                        MARIUS              RECULET   4.0     4.0   0.0
450931                   MELISSANDRE                RIAUD  16.0    15.0   1.0
441018                         LUCIE              RIVIERE  11.0     9.0   2.0
458551                         ALAIA        ROBIN--DEGUIL   8.0     4.0   4.0
461847                       KAMERON               ROUYAT   3.0     1.0   2.0
454123                      NOUHAILA                SAIDI   0.0     0.0   0.0
455153                        ROXANE                 SAIS   4.0     0.0   4.0
460084                      COPPELIA                SEYDI  14.0    12.0   2.0
459660                      BEATRICE              SOUCHET  15.0    14.0   1.0
458747                         ELISA             SPECOGNA  12.0     8.0   4.0
460488                         ADELE              STIDLER  19.0    19.0   0.0

[89 rows x 5 columns]

In [53]:
with pd.ExcelWriter(notesNom,mode='a',engine='openpyxl') as writer: 
    dfNotes[u"Prénom Nom Note NoteCC Gain".split(" ")].to_excel(writer, sheet_name=u'eCampus',encoding="utf8")